name: dialy news update

on:
  schedule:
    - cron: "30 11 * * *" #runs at 11:30 UTC everyday
  workflow_dispatch:

jobs:
  runNewsUpdateScript:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2
      - name: install deps
        run: bun install
      - name: build
        run: bun run build
      - name: run
        run: bun run run
      - name: commit feed
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "crongenerated"
          git push
